#!/bin/bash

BRANCH=$(git rev-parse --abbrev-ref HEAD)
REGEX="^((feature|bug|bugfix|fix)#([0-9]+)|dev)$"

if ! [[ $BRANCH =~ $REGEX ]]; then
  echo "Your commit was rejected due to branching name"
  echo "Please rename your branch with '(feature|bug|bugfix|fix)#id-issue' syntax"
  exit 1
fi
