#!/bin/bash

MESSAGE=$(cat $1)
COMMITFORMAT="^((feature|fix|docs|refactor|test|chore|perf|other)(\((.*)\))?: #([0-9]+)|(Merge|Bumping|docs: Update documentation)) (.*)$"
if ! [[ "$MESSAGE" =~ $COMMITFORMAT ]]; then
  echo "Your commit was rejected due to the commit message. Skipping..."
  echo ""
  echo "Please use the following format:"
  echo "feature: #1234 feature example comment"
  echo "fix(ui): #4321 bugfix example comment"
  echo ""
  echo "More details on COMMITS.md"
  exit 1
fi
