name: GWA Flow

on:
  pull_request:
    branches: [main, dev]
  push:
    tags:
      - "*.*.*"
      - "*.*.*-alpha.*"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade poetry
        poetry install

    - name: Test with tox
      run: poetry run tox

    - name: Generate coverage report
      run: |
        poetry run pytest -v --cov=./incolumepy --cov-report=xml

  build:
    name: Build package release
    runs-on: "ubuntu-latest"
    needs: [test]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade poetry
          poetry install

      - name: Build with poetry
        run: |
          poetry build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        if: success()   # failure():: => contexts#job-status-check-functions
        with:
          name: build-package
          path: dist/
          if-no-files-found: error   # 'error', 'warn' or 'ignore' are also available, defaults to `warn`

  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    needs: [build]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build-package
          path: dist/

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            dist/*

  publish-testpypi:
    name: Publish Test PyPI
    runs-on: ubuntu-latest
    needs: [tagged-release]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade poetry
          poetry install

      - name: Configure repository access
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config pypi-token.testpypi ${{ secrets.TEST_PYPI_TOKEN }}

      - uses: actions/download-artifact@v2
        with:
          name: build-package
          path: dist/

      - name: Publish to testpypi
        run: |
          poetry publish -r testpypi

  publish-pypi:
    name: Publish PyPI
    runs-on: ubuntu-latest
    needs: [tagged-release]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade poetry
          poetry install

      - name: Configure repository access
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

      - uses: actions/download-artifact@v2
        with:
          name: build-package
          path: dist/

      - name: Publish to pypi
        run: |
          poetry publish
