name: GWA Release   # Fail
on:
  workflow_run:
    workflows: ["Tests CI/CD"]
    push:
      tags:
        - "*.*.*"
        - "*.*.*-alpha.*"
    types:
      - completed
jobs:
  build:
    name: Create env and build pack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install poetry
        run: |
          python -m pip install --upgrade poetry

      - name: Build package release
        run: |
          poetry build

      - uses: actions/upload-artifact@v2
        if: success()   # failure():: => contexts#job-status-check-functions
        with:
          name: build-package
          path: dist/
          if-no-files-found: error   # 'error', 'warn' or 'ignore' are also available, defaults to `warn`

#  releases:
#    name: Releases
#    runs-on: ubuntu-latest
#    needs: [build]
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Create Release
#        id: create_release
#        uses: actions/create-release@latest
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ github.ref }}
#          release_name: Release ${{ github.ref }}
#          body: |
#            ${{ steps.Changelog.outputs.changelog }}
#          draft: false
#          prerelease: false

  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    needs: [build]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: build-package
          path: dist/

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            dist/*

  publish-testpypi:
    name: Publish Test PyPI
    runs-on: ubuntu-latest
    needs: [tagged-release]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade poetry
          poetry install

      - name: Configure repository access
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config pypi-token.testpypi ${{ secrets.TEST_PYPI_TOKEN }}

      - uses: actions/download-artifact@v2
        with:
          name: build-package
          path: dist/

      - name: Publish to testpypi
        run: |
          poetry publish -r testpypi

  publish-pypi:
    name: Publish PyPI
    runs-on: ubuntu-latest
    needs: [tagged-release]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade poetry
          poetry install

      - name: Configure repository access
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

      - uses: actions/download-artifact@v2
        with:
          name: build-package
          path: dist/

      - name: Publish to pypi
        run: |
          poetry publish
