name: Poetry Mine Pypi Autopublish    # Success Run
on:
  workflow_run:
    workflows: ["Tests CI/CD"]
    branches: [main]
    types:
      - completed
jobs:
  publish_testpypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade poetry
          poetry install

      - name: Configure repository access
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

      - name: Build package
        run: |
          poetry build

      - name: Publish to pypi
        run: |
          poetry publish

