name: Poetry Test PyPI Manual Publish

on: workflow_dispatch

jobs:
  publish-Test-PyPI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade poetry
          poetry install

      - name: Configure repository access
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config pypi-token.testpypi ${{ secrets.TEST_PYPI_TOKEN }}

      - name: Build a binary wheel and a source tarball
        run: >-
          poetry build

      - name: Publish distribution 📦 to Test PyPI
        run: |
          poetry publish -r testpypi
