name: Poetry Multiprocess
on:
  workflow_run:
    workflows: ["Tests CI/CD"]
    branches: [main]
    types:
      - completed
jobs:
  build:
    name: Create env and build pack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade poetry
          poetry install

      - name: Configure repository access
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config pypi-token.testpypi ${{ secrets.TEST_PYPI_TOKEN }}

      - name: Build package release
        run: |
          poetry build

      - uses: actions/upload-artifact@v2
        if: success()   # failure():: => contexts#job-status-check-functions
        with:
          name: build-package
          path: dist/
          if-no-files-found: error   # 'error', 'warn' or 'ignore' are also available, defaults to `warn`

  publish-testpypi:
    name: Publish Test PyPI
    needs: [build]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: build-package
          path: dist/

      - name: Publish to testpypi
        run: |
          poetry publish -r testpypi

  publish-pypi:
    name: Publish PyPI
    needs: [build]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: build-package
          path: dist/

      - name: Publish to pypi
        run: |
          poetry publish
