name: poetry-mine-publish-automatically
on:
  workflow_run:
    workflows: ["Tests CI/CD"]
    branches: [dev, main]
    types:
      - completed
jobs:
  publish_pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade poetry
          poetry install

      - name: Configure repository access
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

      - name: Build package version
        run: |
          poetry build

      - name: Publish to pypi
        if: startsWith(github.ref, 'refs/heads/main')
        run: |
          poetry publish

  publish_testpypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade poetry
          poetry install

      - name: Configure repository access
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config pypi-token.testpypi ${{ secrets.TEST_PYPI_TOKEN }}

      - name: Build package version
        run: |
          poetry build

      - name: Publish to testpypi
        if: startsWith(github.ref, 'refs/heads/dev')
        run: |
          poetry publish -r testpypi

