name: Poetry Mine Testpypi Autopublish    # Fail in publish prerelease from repo@dev publish only repo@main
on:
  workflow_run:
    workflows: ["Tests CI/CD"]
    branches: [dev]
    types:
      - completed
jobs:
  publish_testpypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade poetry
          poetry install

      - name: Configure repository access
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config pypi-token.testpypi ${{ secrets.TEST_PYPI_TOKEN }}

      - name: Build package
        run: |
          poetry build

      - name: Publish to testpypi
        run: |
          poetry publish -r testpypi

